map<string, string> statDict = {
	{ "Aerial Goal", "aerialGoals" },
	{ "Aerial Hit", "aerialHits" },
	{ "Backwards Goal", "backwardsGoals" },
	{ "Ball Touch", "ballTouches" },
	{ "Bicycle Goal", "bicycleGoals" },
	{ "Bicycle Hit", "bicycleHits" },
	{ "Boost Pickup", "boostPickups" },
	{ "Center Ball", "centers" },
	{ "Clear Ball", "clears" },
	{ "Damage", "damages" },
	{ "Epic Save", "epicSaves" },
	{ "Extermination", "exterms" },
	{ "First Touch", "firstTouches" },
	{ "Hat Trick", "hatTricks" },
	{ "High Five", "highFives" },
	{ "Long Goal", "longGoals" },
	{ "Low Five", "lowFives" },
	{ "Overtime Goal", "overtimeGoals" },
	{ "Playmaker", "playmakers" },
	{ "Pool Shot", "poolShots" },
	{ "Save", "saves" },
	{ "Savior", "saviors" },
	{ "Swish Goal", "swishes" },
	{ "Turtle Goal", "turtleGoals" },
	{ "Ultra Damage", "ultraDamages" },
};

map<string, string> arenaDict = {
  { "Underwater_P", "AquaDome" },
  { "NeoTokyo_Standard_P", "Neo Tokyo" },
  { "UtopiaStadium_Dusk_P", "Utopia Coliseum (Dusk)" },
  { "music_p", "Neon Fields" },
  { "ShatterShot_P", "Core 707" },
  { "wasteland_s_p", "Wasteland" },
  { "wasteland_Night_S_P", "Wasteland (Night)" },
};